import type { Detector, DetectorPattern } from "./types.js";

const patterns: DetectorPattern[] = [
  {
    id: "DNG001",
    regex: /\beval\s*\(/,
    category: "dangerous",
    severity: "high",
    message: "eval() call detected — arbitrary code execution risk",
    remediation: "Avoid eval(); use safer alternatives",
  },
  {
    id: "DNG002",
    regex: /\bnew\s+Function\s*\(/,
    category: "dangerous",
    severity: "high",
    message: "new Function() detected — dynamic code execution risk",
    remediation: "Avoid dynamic code generation",
  },
  {
    id: "DNG003",
    regex: /\bchild_process\b/,
    category: "dangerous",
    severity: "high",
    message: "child_process module usage detected",
    remediation: "Declare required commands in permissions.exec",
  },
  {
    id: "DNG004",
    regex: /\b(exec|execSync|spawn|spawnSync|execFile|execFileSync|fork)\s*\(/,
    category: "dangerous",
    severity: "high",
    message: "Process execution function detected",
    remediation: "Declare required commands in permissions.exec",
  },
  {
    id: "DNG005",
    regex: /curl\s+.*\|\s*sh/,
    category: "dangerous",
    severity: "critical",
    message: "curl | sh pipe execution detected — remote code execution risk",
    remediation: "Download and verify scripts before executing",
  },
  {
    id: "DNG006",
    regex: /rm\s+-rf\s+[/~]/,
    category: "dangerous",
    severity: "critical",
    message: "Destructive rm -rf command detected",
    remediation: "Use targeted file removal instead",
  },
  {
    id: "DNG007",
    regex: /\bfs\.(writeFile|writeFileSync|appendFile|appendFileSync|rmSync|rmdirSync|unlinkSync)\s*\(/,
    category: "dangerous",
    severity: "high",
    message: "Filesystem write/delete operation detected",
    remediation: "Declare paths in permissions.filesystem",
  },
  {
    id: "DNG008",
    regex: /process\.env[\s\S]{0,50}(fetch|http|request|send|post|XMLHttpRequest)/,
    category: "dangerous",
    severity: "critical",
    message: "Potential environment variable exfiltration detected",
    remediation: "Do not send environment variables to external services",
  },
  {
    id: "DNG009",
    regex: /\bwget\s+/,
    category: "dangerous",
    severity: "medium",
    message: "wget usage detected",
    remediation: "Declare network access in permissions.network",
  },
  {
    id: "DNG010",
    regex: /\b(nc|ncat|netcat)\s+(-[a-z]*\s+)*\S+\s+\d+/,
    category: "dangerous",
    severity: "critical",
    message: "Reverse shell pattern detected (netcat)",
    remediation: "Remove reverse shell code",
  },
  {
    id: "DNG011",
    regex: /\/dev\/(tcp|udp)\/\S+\/\d+/,
    category: "dangerous",
    severity: "critical",
    message: "Reverse shell pattern detected (/dev/tcp)",
    remediation: "Remove reverse shell code",
  },
  {
    id: "DNG012",
    regex: /process\.env\.(HOME|USER|PATH|SHELL|LOGNAME)/,
    category: "dangerous",
    severity: "medium",
    message: "Environment variable access detected",
    remediation: "Ensure environment variables are used locally only",
  },
];

export const dangerousDetector: Detector = {
  name: "dangerous",
  patterns,
};
